# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da35ad4404579cfd5bd04ae7a3f3b1ca41db93a1e2bc644b4a91b520fde438bbc2091ee9b0fe6c3a066dff2e0f1e2e3b90303214f110860c75fe6a0d99aac6d5

test:
  secret_key_base: 446040e49ed8c122a78c3c52d73ed55ce58572e3e2499f926e173c5f93b45d0822c3483cd960741e534a6c8c39cd72ba6203da1023d404a2c0f849656d15514c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
